version: '3.3'
services:
  elk:
    build: .
    image: "elk_local"
    container_name: elk_local
    restart: always
    ports:
      - "5601:5601"
      - "9200:9200"
      - "5044:5044"
    volumes:
      - ./conf/:/opt/bin/
      - ./logstash:/etc/logstash/conf.d
      - ./elasticsearch:/var/lib/elasticsearch
      - ./logs:/home/logs
      - ./filebeat/:/etc/filebeat/
    command: bash -c 'service filebeat start && opt/logstash/bin/logstash-plugin install logstash-filter-aggregate && /usr/local/bin/start.sh '
